# Generated by Django 6.0.2 on 2026-03-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelApp_7', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskanddeadlineplanner',
            name='completionStatus',
            field=models.CharField(default=0),
        ),
    ]
