print("Question_1")
 # (initailizing the details using datatypes)
emp_id=10
emp_name="yazhini"
emp_email="yalini@gmail.com"
emp_phone_no=1234567890
emp_salary=68000
emp_gender="F"
emp_city="Thanjavur"
print(emp_id)
print(emp_name)
print(emp_email)
print(emp_phone_no)
print(emp_salary)
print(emp_gender)
print(emp_city)

print("Question-2")
# student_Id=int(input("Enter Student ID:"))
# student_name=input("Enter Student Name:")
# mark_1=int(input("Enter Mark 1:"))
# mark_2=int(input("Enter Mark 2:"))
# mark_3=int(input("Enter Mark 3:"))
# mark_4=int(input("Enter Mark 4:"))
# total=mark_1+mark_2+mark_3+mark_4
# average=total/4
# print(total)
# print(average)

print("Question-3")
# student_Id=int(input("Enter Student ID:"))
# student_Name=input("Enter Student Name:")
# student_Email=input("Enter Student Email:")
# student_Phone_no=input("Enter Student Phone No:")
# student_Department=input("Enter Student Department:")
# student_Gender=input("Enter Student Gender:")
# student_City=input("Enter Student City:")

print("Question-4")
# clg_Id=int(input("Enter CLG ID:"))
# clg_Name=str(input("Enter CLG Name:"))
# clg_Email=str(input("Enter CLG Email:"))
# clg_Phone_no=int(input("Enter CLG Phone No:"))
# clg_Department_Count=str(input("Enter CLG Department_count:"))
# clg_Code=int(input("Enter CLG Code:"))
# clg_Address=str(input("Enter CLG Address:"))

print("Question-5")
# com_Id=int(1)
# com_Name=str("yazhini")
# com_Email=str("yalini@gamil.com")
# com_Phone_no=str("1234567890")
# com_Employee_Count=int(67)
# com_Location=str("Thanjavur")
# com_CEO=str("yazhini")
# com_Founded_date=str("Jan1999")
# print(com_Id)
# print(com_Name)
# print(com_Email)
# print(com_Phone_no)
# print(com_Employee_Count)
# print(com_Location)
# print(com_CEO)
# print(com_Founded_date)

print("Question-6")
# bank_id=input("enetr your bank id")
# bank_name=input("enetr your bank name")
# branch_name=input("enetr your branch name")
# ifsc_code=input("enetr your ifsc code")
# account_no=input("enetr your account number")
# account_type=input("enetr your account type")
# holder_name=input("enetr your holder name")
# mobile_no=input("enetr your mobile number")
# email=input("enetr your email address")
# address=input("enetr your address")
# city=input("enetr your city")
# state=input("enetr your state")
# country=input("enetr your country")
# balance=input("enetr your balance")
# opening_date=input("enetr your opening date")
# print(bank_id)
# print(bank_name)
# print(branch_name)
# print(account_no)
# print(account_type)
# print(holder_name)
# print(mobile_no)
# print(email)
# print(address)
# print(city)
# print(state)
# print(country)
# print(balance)
# print(opening_date)

print("Question-7")
# states=[]
# n=int(input("enter number of states:"))
# for i in range(n):
#     state=input("enter state:")
#     states.append(state)
# print("States in India:")
# for s in states:
#     print(s)

print("Question-8")
# district_state=input("Enter district state")
# district_name=input("Enter district name")
# district_area=input("Enter district area")
# district_population=input("Enter district population")
# district_capital=input("Enter district capital")
# district_urban_count=input("Enter district urban count")
# district_rural_count=input("Enter district rural count")
# print(district_state,district_name,district_area,district_urban_count,district_rural_count)
