# Generated by Django 6.0.2 on 2026-03-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryStockManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockQuantity', models.IntegerField()),
                ('supplierName', models.CharField(max_length=100)),
                ('purchaseDate', models.DateField()),
                ('reorderLevel', models.IntegerField()),
            ],
        ),
    ]
