# Generated by Django 6.0.2 on 2026-03-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalHealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits', models.IntegerField(default=0)),
                ('diagnosis', models.IntegerField(default=0)),
                ('medicines', models.IntegerField(default=0)),
                ('orderStatus', models.CharField(default=0)),
            ],
        ),
    ]
