# Generated by Django 6.0.2 on 2026-03-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelApp_6', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalhealthrecord',
            name='orderStatus',
        ),
        migrations.AddField(
            model_name='personalhealthrecord',
            name='followDates',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personalhealthrecord',
            name='diagnosis',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
