# Generated by Django 6.0.2 on 2026-03-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyExpenseTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('paymentMode', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
