# Generated by Django 6.0.2 on 2026-03-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantOrderManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=100)),
                ('itemQuantity', models.IntegerField()),
                ('itemPrice', models.IntegerField()),
                ('orderTime', models.DateTimeField()),
                ('orderStatus', models.BooleanField()),
            ],
        ),
    ]
