# Generated by Django 6.0.3 on 2026-03-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperMarketSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productOne', models.CharField(max_length=200)),
                ('productTwo', models.CharField(max_length=200)),
                ('productThree', models.CharField(max_length=200)),
                ('totalPrice', models.IntegerField()),
                ('customerName', models.CharField(max_length=200)),
                ('phoneNo', models.IntegerField()),
                ('loyaltyPoints', models.IntegerField()),
            ],
        ),
    ]
