# Generated by Django 6.0.2 on 2026-03-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=100)),
                ('admissionNo', models.IntegerField()),
                ('standard', models.CharField()),
                ('bloodGroup', models.CharField()),
                ('address', models.CharField()),
            ],
        ),
    ]
