# Generated by Django 6.0.2 on 2026-03-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalPropertyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyName', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('rentAmount', models.IntegerField(default=0)),
                ('ownerDetails', models.CharField(max_length=100)),
                ('availabilityStatus', models.CharField(max_length=100)),
            ],
        ),
    ]
